Repository sequentech/common-ui, pull requests merged in 2023-09, with the labels that each got.

#334 🐞 pop up election-id to long
  avUi/common-header-directive/common-header-directive.less
  dist/less/avUi/common-header-directive/common-header-directive.less
  dist/themes/default/app.min.css
  dist/themes/podemos/app.min.css
  dist/themes/test/app.min.css
  dist/themes/v2/app.min.css
Labels: bug

#335 🐞 pop up election-id to long
  avUi/common-header-directive/common-header-directive.less
  dist/less/avUi/common-header-directive/common-header-directive.less
  dist/themes/default/app.min.css
  dist/themes/podemos/app.min.css
  dist/themes/test/app.min.css
  dist/themes/v2/app.min.css
Labels: bug

#336 🐞 pop up election-id to long
  avUi/common-header-directive/common-header-directive.less
  dist/less/avUi/common-header-directive/common-header-directive.less
  dist/themes/default/app.min.css
  dist/themes/podemos/app.min.css
  dist/themes/test/app.min.css
  dist/themes/v2/app.min.css
Labels: bug

#337 alternative auth methods: switch back to smartlink tab fails (#333)
  avRegistration/login-directive/login-directive.html
  avRegistration/login-directive/login-directive.js
  dist/appCommon-vmaster.js
  dist/img/cropped-FAV-6-180x180.png
  dist/img/cropped-FAV-6-192x192.png
  dist/img/sequent_voting_logo_100.png
Labels: bug

#338 Bump semver from 5.7.1 to 5.7.2 (#323)
  package.json
  yarn.lock
Labels: dependencies

#339 Bump tough-cookie to 4.1.3
  dist/img/cropped-FAV-6-180x180.png
  dist/img/cropped-FAV-6-192x192.png
  dist/img/sequent_voting_logo_100.png
  package.json
  yarn.lock
Labels: dependencies

#340 Bump tough-cookie to 4.1.3 (#339)
  package.json
  yarn.lock
Labels: dependencies

#343 Add italian language support
  Gruntfile.js
  dist/locales/it.json
  locales/it.json
Labels: enhancement

#342 Automated start/stop support
  avRegistration/auth-method-service.js
  avUi/election-creation.js
  dist/appCommon-v9.1.0.js
Labels: enhancement

#346 🐞 Resend auth codes in email-otl or sms-otp doesn't work in alt-auth-method (#345)
  avRegistration/login-directive/login-directive.js
  dist/appCommon-vmaster.js
Labels: bug

#347 Fix uri params with spaces
  avRegistration/login-directive/login-directive.js
  dist/appCommon-v10.0.0.js
Labels: bug
