Repository sequentech/common-ui, pull requests merged in 2023-06, with the labels that each got.

#306 Bump socket.io-parser from 4.0.4 to 4.2.3 (#305)
  package.json
  yarn.lock
Labels: dependencies

#308 Include Manrope and other fonts in the fonts folder
  dist/fonts/Manrope-VariableFont_wght.ttf
  dist/themes/fonts/Manrope-VariableFont_wght.ttf
  fonts
  fonts/Manrope-VariableFont_wght.ttf
  fonts/glyphicons-halflings-regular.eot
  fonts/glyphicons-halflings-regular.svg
  fonts/glyphicons-halflings-regular.ttf
  fonts/glyphicons-halflings-regular.woff
  fonts/glyphicons-halflings-regular.woff2
Labels: bug

#309 ✨ Shrink header/footer
  avUi/common-footer-directive/common-footer-directive.less
  avUi/common-header-directive/common-header-directive.less
  dist/less/avUi/common-footer-directive/common-footer-directive.less
  dist/less/avUi/common-header-directive/common-header-directive.less
  dist/themes/default/app.min.css
  dist/themes/podemos/app.min.css
  dist/themes/test/app.min.css
  dist/themes/v2/app.min.css
Labels: enhancement

#311 ✨ Shrink header/footer (#309)
  avUi/common-footer-directive/common-footer-directive.less
  avUi/common-header-directive/common-header-directive.less
  dist/less/avUi/common-footer-directive/common-footer-directive.less
  dist/less/avUi/common-header-directive/common-header-directive.less
  dist/themes/default/app.min.css
  dist/themes/podemos/app.min.css
  dist/themes/test/app.min.css
  dist/themes/v2/app.min.css
Labels: enhancement

#312 Alternative Auth methods support
  avRegistration/fields/tel-field-directive/tel-field-directive.less
  avRegistration/login-controller/login-controller.html
  avRegistration/login-controller/login-controller.js
  avRegistration/login-directive/login-directive.html
  avRegistration/login-directive/login-directive.js
  avRegistration/login-directive/login-directive.less
  avUi/election-creation.js
  dist/appCommon-v8.0.1.js
  dist/locales/en.json
  dist/themes/default/app.min.css
  dist/themes/podemos/app.min.css
  dist/themes/test/app.min.css
  dist/themes/v2/app.min.css
  locales/en.json
Labels: enhancement

#313 Alternative Auth methods support (#312)
  avRegistration/fields/tel-field-directive/tel-field-directive.less
  avRegistration/login-controller/login-controller.html
  avRegistration/login-controller/login-controller.js
  avRegistration/login-directive/login-directive.html
  avRegistration/login-directive/login-directive.js
  avRegistration/login-directive/login-directive.less
  avUi/election-creation.js
  dist/appCommon-v8.0.0.js
  dist/locales/en.json
  dist/themes/default/app.min.css
  dist/themes/podemos/app.min.css
  dist/themes/test/app.min.css
  dist/themes/v2/app.min.css
  locales/en.json
Labels: enhancement

#316 Improve authentication messages to users
  Gruntfile.js
  SequentConfig.js
  avRegistration/login-directive/login-directive.html
  avRegistration/login-directive/login-directive.js
  dist/SequentConfig-vmaster.js
  dist/SequentPlugins-vmaster.js
  dist/SequentThemes-vmaster.js
  dist/appCommon-vmaster.js
  dist/img/cropped-FAV-6-180x180.png
  dist/img/cropped-FAV-6-192x192.png
  dist/img/sequent_voting_logo_100.png
  dist/index.html
  dist/libCommon-vmaster.js
  dist/libnocompat-vmaster.js
  dist/locales/en.json
  dist/themes/fonts/Manrope-VariableFont_wght.ttf
  locales/en.json
  package.json
Labels: enhancement, breaking-change

#315 🐞French translation is tagged as English
  avUi/common-header-directive/common-header-directive.less
  dist/less/avUi/common-header-directive/common-header-directive.less
  dist/locales/fr.json
  dist/themes/default/app.min.css
  dist/themes/podemos/app.min.css
  dist/themes/test/app.min.css
  dist/themes/v2/app.min.css
  locales/fr.json
Labels: bug

#317 🐞French translation is tagged as English (#315)
  avUi/common-header-directive/common-header-directive.less
  dist/less/avUi/common-header-directive/common-header-directive.less
  dist/locales/fr.json
  dist/themes/default/app.min.css
  dist/themes/podemos/app.min.css
  dist/themes/test/app.min.css
  dist/themes/v2/app.min.css
  locales/fr.json
Labels: bug

#314 ✨ Countdown until logout
  SequentConfig.js
  avRegistration/auth-method-service.js
  avRegistration/login-directive/login-directive.js
  avRegistration/openid-connect-directive/openid-connect-directive.js
  avUi/common-header-directive/common-header-directive.html
  avUi/common-header-directive/common-header-directive.js
  avUi/common-header-directive/common-header-directive.less
  dist/SequentConfig-vmaster.js
  dist/appCommon-vmaster.js
  dist/img/cropped-FAV-6-180x180.png
  dist/img/cropped-FAV-6-192x192.png
  dist/img/sequent_voting_logo_100.png
  dist/less/avUi/common-header-directive/common-header-directive.less
  dist/themes/default/app.min.css
  dist/themes/podemos/app.min.css
  dist/themes/test/app.min.css
  dist/themes/v2/app.min.css
Labels: enhancement, breaking-change

#318 🐞Fix ui deployment
  Gruntfile.js
  SequentConfig.js
  dist/SequentConfig-v8.0.0.js
  dist/SequentPlugins-v8.0.0.js
  dist/SequentThemes-v8.0.0.js
  dist/appCommon-v8.0.0.js
  dist/index.html
  dist/libCommon-v8.0.0.js
  dist/libnocompat-v8.0.0.js
Labels: bug

#319 ✨ countdown until timeout
  Gruntfile.js
  SequentConfig.js
  avUi/common-header-directive/common-header-directive.less
  dist/SequentConfig-v8.0.0.js
  dist/SequentPlugins-v8.0.0.js
  dist/SequentThemes-v8.0.0.js
  dist/appCommon-v8.0.0.js
  dist/index.html
  dist/less/avUi/common-header-directive/common-header-directive.less
  dist/libCommon-v8.0.0.js
  dist/libnocompat-v8.0.0.js
  dist/themes/default/app.min.css
  dist/themes/podemos/app.min.css
  dist/themes/test/app.min.css
  dist/themes/v2/app.min.css
Labels: enhancement, breaking-change
