Repository sequentech/common-ui, pull requests merged in 2023-01, with the labels that each got.

#268 Migrate from ORT github action to reusable ORT workflow
  .github/workflows/ort.yml
Labels: infrastructure

#269 Migrate from ORT github action to reusable ORT workflow
  .github/workflows/ort.yml
Labels: infrastructure

#264 Live preview
  avUi/election-creation.js
  dist/appCommon-vmaster.js
  dist/libCommon-vmaster.js
  index.html
Labels: enhancement

#270 Live preview (#264)
  avUi/election-creation.js
  dist/appCommon-v7.1.1.js
  index.html
Labels: enhancement

#271 Election IDs automation (#267)
  avRegistration/auth-method-service.js
  dist/appCommon-v7.1.1.js
Labels: enhancement

#276 Show success on login after registration
  avRegistration/login-directive/login-directive.html
  avRegistration/login-directive/login-directive.js
  avRegistration/login-directive/login-directive.less
  avRegistration/register-directive/register-directive.js
  dist/appCommon-v7.1.1.js
  dist/libCommon-v7.1.1.js
  dist/locales/ca.json
  dist/locales/en.json
  dist/locales/es.json
  dist/locales/fr.json
  dist/themes/bcnencomu/app.min.css
  dist/themes/cup/app.min.css
  dist/themes/default/app.min.css
  dist/themes/diba/app.min.css
  dist/themes/ebcn/app.min.css
  dist/themes/helsinki/app.min.css
  dist/themes/loop/app.min.css
  dist/themes/podemos/app.min.css
  dist/themes/test/app.min.css
  locales/ca.json
  locales/en.json
  locales/es.json
  locales/fr.json
Labels: enhancement

#277 Avoid sending otp twice on registration
  avRegistration/login-directive/login-directive.js
  dist/appCommon-v7.1.1.js
Labels: bug
