Repository sequentech/common-ui, pull requests merged in 2024-04, with the labels that each got.

#389 ✨ Download election turnout (#387)
  avRegistration/auth-method-service.js
  dist/appCommon-vmaster.js
Labels: enhancement

#388 🐞 OIDC: Use Authorization Code Flow instead of implicit flow
  avRegistration/login-directive/login-directive.js
  dist/appCommon-v10.3.0.js
Labels: bug

#391 🐞 OIDC: Use Authorization Code Flow instead of implicit flow (#388)
  avRegistration/login-directive/login-directive.js
  dist/appCommon-vmaster.js
Labels: bug

#390 🐞 smartlink as alternative auth method
  avRegistration/login-directive/login-directive.html
  avRegistration/login-directive/login-directive.js
  dist/appCommon-v10.3.0.js
Labels: bug

#392 🐞 smartlink as alternative auth method (#390)
  avRegistration/login-directive/login-directive.html
  avRegistration/login-directive/login-directive.js
  dist/appCommon-vmaster.js
Labels: bug

#393 🛡 Security updates
  package.json
  yarn.lock
Labels: dependencies
